# Generated by Django 3.1.6 on 2021-02-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0002_auto_20210224_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterModelOptions(
            name='motorizados',
            options={'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'verbose_name': 'Telefono', 'verbose_name_plural': 'Telefonos'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={},
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='tipo',
            field=models.CharField(auto_created=True, default='bicicleta', max_length=50, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='motorizados',
            name='tipo',
            field=models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto'), ('camion', 'Camion')], default='auto', max_length=50, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(auto_created=True, default='telefono', max_length=50, verbose_name='tipo'),
        ),
    ]
