# Generated by Django 3.1.6 on 2021-02-24 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0003_auto_20210224_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('bienespersonales_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bienes.bienespersonales')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('negocio', 'Negocio')], default='casa', max_length=50, verbose_name='tipo')),
                ('metros', models.IntegerField(verbose_name='Metros Cubiertos')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
            bases=('bienes.bienespersonales',),
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
    ]
