# Generated by Django 3.1.6 on 2021-02-26 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0004_auto_20210224_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bienes.bienespersonales', verbose_name='Bien Personal'),
        ),
    ]
