# Generated by Django 3.1.6 on 2021-02-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0006_auto_20210226_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='IME',
            field=models.CharField(max_length=50, verbose_name='IME'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='Caracteristicas'),
        ),
    ]
