# Generated by Django 3.1.6 on 2021-02-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0008_motorizados_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='ciudad',
            field=models.CharField(default='pinamar', max_length=50, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='provicia',
            field=models.CharField(choices=[('B', 'Buenos Aires'), ('K', 'Catamarca'), ('H', 'Chaco'), ('U', 'Chubut'), ('C', 'Ciudad Autónoma de Buenos Aires'), ('X', 'Córdoba'), ('W', 'Corrientes'), ('E', 'Entre Ríos'), ('P', 'Formosa'), ('Y', 'Jujuy'), ('L', 'La Pampa'), ('F', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('Q', 'Neuquén'), ('R', 'Río Negro'), ('A', 'Salta'), ('J', 'San Juan'), ('D', 'San Luis'), ('Z', 'Santa Cruz'), ('S', 'Santa Fe'), ('G', 'Santiago del Estero'), ('V', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'), ('T', 'Tucumán')], default='b', max_length=50, verbose_name='Provincia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='zip_code',
            field=models.IntegerField(default=7167, verbose_name='Codigo Postal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='metros',
            field=models.IntegerField(verbose_name='Superficie'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='tipo',
            field=models.CharField(choices=[('depto en 3er piso o superior', 'Depto en 3er piso o superior'), ('casa', 'Casa o Depto en planta baja, 1er, 2do piso'), ('barrio privado', 'Barrio Privado'), ('casa de finde', 'Casa de fin de semana (no en barrio privado)'), ('negocio', 'Negocio')], default='casa', max_length=50, verbose_name='tipo de vivenda'),
        ),
    ]
