# Generated by Django 3.1.6 on 2021-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0010_vivienda_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='valor',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='valor',
            field=models.IntegerField(default=0, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='bienespersonales',
            name='valor',
            field=models.IntegerField(default=0, verbose_name='Valor'),
        ),
    ]
